name: Publish Plugin to Portal

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :plugin:check

      - name: Publish on Plugin Portal
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :plugin:publishPlugins
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
