name: Run unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
