name: Run unit tests

on:
  push:
  pull_request:

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :plugin:check
