name: Run unit tests

on:
  push:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :plugin:check
